export const ActionTypes = {
    ADD_MOVIE: "ADD_MOVIE",
    GET_MOVIES: "GET_MOVIES",
    GET_MOVIES_BY_ID: "GET_MOVIES_BY_ID",
    UPDATE_MOVIE: "UPDATE_MOVIE",
    ADD_ACTOR: "ADD_ACTOR",
    ADD_PRODUCER: "ADD_PRODUCER"
}